### ISSUE TITLE
Why no default export?

### ISSUE THREAD

**Issue by binarykitchen** [calvinmetcalf/buffer-es6#2]
When using rollupjs as a bundler and is using your library as a nested dependency within my project, then I see this warning from rollupjs

```bash
$ rollup (removed)
bundling...
100% (766): src/(removed)⚠️   'default' is not exported by 'node_modules/buffer-es6/index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:(removed)/node_modules/buffer-es6/index.js (1:137)
1: import * as index from "(removed)/node_modules/buffer-es6/index.js"; export default ( index && index['default'] ) || index;
```

have you ever tried bundling your package with rollup? 

if not, give it a try and see if you can do it (this to reproduce the above), otherwise do you have a rollup recipe that makes bundling work with your package?

**Comment by calvinmetcalf** [comment]
`import {Buffer} from 'buffer-es6' `

or if you just want `Buffer.isBuffer`

`import {isBuffer} from 'buffer-es6' `

this was written with [rollup-plugin-node-globals](https://github.com/calvinmetcalf/rollup-plugin-node-globals) and [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins) in mind.

your actually issue may have to do with the commonjs plugin possibly trying to do something to this module

**Comment by binarykitchen** [comment]
hmmm, do you have a recipe to tell the commonjs plugin how to deal with this buffer-es6 module? 

for a starter, this is my current rollup config
https://github.com/binarykitchen/videomail-client/blob/feature/rollupjs/env/dev/rollup.config.js

any ideas @calvinmetcalf ?

**Comment by calvinmetcalf** [comment]
try reordering your plugins like this

```
     globals(),
     builtins(),
     nodeResolve({ jsnext: true, main: true, browser: true }),
     commonjs({
       ignoreGlobal: true
     }),

```

**Comment by binarykitchen** [comment]
ok, when reordered, that buffer-es6 error is gone, but now seeing new errors but they are probably not related to your repo.

maybe you want to document in the readme the above recommended order of plugins?

**Comment by binarykitchen** [comment]
and btw, i the new errors after reordering are

```
~/c/videomail-client ❯❯❯ npm run build:dev                                              ⏎ feature/rollupjs ✭ ✱ ◼

> videomail-client@1.28.11 prebuild:dev /home/michael-heuberger/code/videomail-client
> npm run std --silent


> videomail-client@1.28.11 build:dev /home/michael-heuberger/code/videomail-client
> rollup -c env/dev/rollup.config.js -w

bundling...
94% (700): src/wrappers/optionsWrapper.js⚠️   'default' is not exported by 'node_modules/global/window.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/michael-heuberger/code/videomail-client/node_modules/global/window.js (1:137)
1: import * as window from "/home/michael-heuberger/code/videomail-client/node_modules/global/window.js"; export default ( window && window['default'] ) || window;
                                                                                                                                            ^

⚠️   'default' is not exported by 'node_modules/global/document.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/michael-heuberger/code/videomail-client/node_modules/global/document.js (1:145)
1: import * as document from "/home/michael-heuberger/code/videomail-client/node_modules/global/document.js"; export default ( document && document['default'] ) || document;
                                                                                                                                                    ^

🚨   'default' is not exported by node_modules/websocket-stream/stream.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/wrappers/visuals/recorder.js (3:7)
1: import { Buffer as Buffer } from "/home/michael-heuberger/code/videomail-client/node_modules/buffer-es6/index.js";
2: 
3: import websocket from 'websocket-stream';
          ^
4: import Frame from 'canvas-to-buffer';
5: import util from 'util';
```

the rollupjs config is at https://github.com/binarykitchen/videomail-client/blob/feature/rollupjs/env/dev/rollup.config.js

no idea how to fix the above :(

**Comment by calvinmetcalf** [comment]
maybe don't use rollup if you have a lot of dependencies in your app, it's really made for libraries where there are only a few dependencies and/or you control them all

**Comment by binarykitchen** [comment]
@calvinmetcalf mmmhh, but it is for a library i am developing, namely videomail-client ...

... if you really dont recommend rollup ... then should i switch to webpack 2 or so? it is just because rollup has better file reduction size and performance than webpack 2 ...

**Comment by calvinmetcalf** [comment]
so I like rollup I think it's really good for certain situations but since it is very much all about es6 style modules if you have dependencies that are not es6 modules it can be VERY troublesome to get them working so it's a tradeoff.

**Comment by binarykitchen** [comment]
got it - learned it the hard way and wasted hours :(
